version: '1.0'
stages:
  - "clone"
  - "deploy"
steps:
  main_clone:
    stage: "clone"
    title: "Cloning repo"
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "samer-shami/demochat"
    git: github
    revision: "${{CF_BRANCH}}"
  RunningDeployScript:
    stage: "deploy"
    title: Running Deploy Script
    type: deploy
    kind: kubernetes
    cluster: uat-bgl360-eks
    namespace: demochat
    # Path to deployment.yml location inside the image volume
    file_path: ./eks_deployment.yml
