version: '1.0'
steps:
  RunningDeployScript:
    title: Running Deploy Script
    type: deploy
    kind: kubernetes
    cluster: uat-bgl360-eks
    namespace: demochat
    when:
      branch:
        only:
          - master
    service: demochat
