version: '1.0'
steps:
  RunningDeployScript:
    title: Running Deploy Script
    type: deploy
    kind: kubernetes
    cluster: uat-bgl360-eks
    namespace: demochat
    # Path to deployment.yml location inside the image volume
    file_path: ./eks_deployment.yml
